// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlTAR_gaFGoZsdC4jM-OGAnMnHZvP3spo',
    appId: '1:264919542032:web:3373a15501f62f8cacdd95',
    messagingSenderId: '264919542032',
    projectId: 'image-compressor-c0aa9',
    authDomain: 'image-compressor-c0aa9.firebaseapp.com',
    storageBucket: 'image-compressor-c0aa9.firebasestorage.app',
    measurementId: 'G-M53SEN45E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPcFQz41fRkAlR-sJataqB5CPEBY-uB6w',
    appId: '1:264919542032:android:554513833ad9f969acdd95',
    messagingSenderId: '264919542032',
    projectId: 'image-compressor-c0aa9',
    storageBucket: 'image-compressor-c0aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBBfGYCOfpchPouQwHYx-t0R83SuBue_k',
    appId: '1:264919542032:ios:c99de1bbbb0038e8acdd95',
    messagingSenderId: '264919542032',
    projectId: 'image-compressor-c0aa9',
    storageBucket: 'image-compressor-c0aa9.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBBfGYCOfpchPouQwHYx-t0R83SuBue_k',
    appId: '1:264919542032:ios:c99de1bbbb0038e8acdd95',
    messagingSenderId: '264919542032',
    projectId: 'image-compressor-c0aa9',
    storageBucket: 'image-compressor-c0aa9.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlTAR_gaFGoZsdC4jM-OGAnMnHZvP3spo',
    appId: '1:264919542032:web:5142f8e2c5b4dcacacdd95',
    messagingSenderId: '264919542032',
    projectId: 'image-compressor-c0aa9',
    authDomain: 'image-compressor-c0aa9.firebaseapp.com',
    storageBucket: 'image-compressor-c0aa9.firebasestorage.app',
    measurementId: 'G-W6G4V4Q09B',
  );
}
